# For more details on how to create your config file 
# https://makgyver.github.io/fluke/configuration.html
data:
  dataset:
    name: mnist
    path: ./data
    channel_dim: true
  distribution:
    name: dir
    beta: 0.1
    balanced: false
  sampling_perc: 1
  client_split: 0.0
  keep_test: true
  server_test: true
  server_split: 0.0 # not used in this case
  uniform_test: false
exp:
  device: cpu
  seed: 42
eval:
  task: classification
  eval_every: 1
  pre_fit: true
  post_fit: true
logger:
  name: Log
  # name: WandBLog
  # project: fedmargin-testing
  # entity: mlgroup
protocol:
  eligible_perc: 1.
  n_clients: 10
  n_rounds: 100
