hyperparameters:
  client:
    batch_size: 64
    local_epochs: 10
    loss: CrossEntropyLoss
    persistency: true
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.00001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
  model: MNIST_2NN
name: fluke.algorithms.fedavg.FedAVG
