hyperparameters:
  client:
    batch_size: 32
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.1
      # momentum: 0.9
      # weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
    k_proportion: 0.8
  model: MNIST_2NN
name: fluke.algorithms.fedld.FedLD
