hyperparameters:
  client:
    batch_size: 128
    local_epochs: 5
    loss: CrossEntropyLoss
    persistency: true
    policy: aggregate
    optimizer:
      lr: 0.1
      momentum: 0.9
      # weight_decay: 0.00001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
  model: MNIST_2NN
name: fluke.algorithms.decentralized.GossipDFL
